[2024-11-25T15:55:19.223+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: kafka_to_snowflake_pipeline.start_kafka_consumer scheduled__2024-11-24T15:54:42.893219+00:00 [queued]>
[2024-11-25T15:55:19.227+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: kafka_to_snowflake_pipeline.start_kafka_consumer scheduled__2024-11-24T15:54:42.893219+00:00 [queued]>
[2024-11-25T15:55:19.227+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-11-25T15:55:19.227+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2024-11-25T15:55:19.227+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-11-25T15:55:19.231+0000] {taskinstance.py:1304} INFO - Executing <Task(_PythonDecoratedOperator): start_kafka_consumer> on 2024-11-24 15:54:42.893219+00:00
[2024-11-25T15:55:19.236+0000] {standard_task_runner.py:55} INFO - Started process 59 to run task
[2024-11-25T15:55:19.237+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'kafka_to_snowflake_pipeline', 'start_kafka_consumer', 'scheduled__2024-11-24T15:54:42.893219+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/kafka_to_snowflake_etl_dag.py', '--cfg-path', '/tmp/tmp8qxdhs7o']
[2024-11-25T15:55:19.239+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask start_kafka_consumer
[2024-11-25T15:55:19.278+0000] {task_command.py:389} INFO - Running <TaskInstance: kafka_to_snowflake_pipeline.start_kafka_consumer scheduled__2024-11-24T15:54:42.893219+00:00 [running]> on host f25f59e56f04
[2024-11-25T15:55:19.309+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Vaibhav Bansal
AIRFLOW_CTX_DAG_ID=kafka_to_snowflake_pipeline
AIRFLOW_CTX_TASK_ID=start_kafka_consumer
AIRFLOW_CTX_EXECUTION_DATE=2024-11-24T15:54:42.893219+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-11-24T15:54:42.893219+00:00
[2024-11-25T15:55:19.312+0000] {kafka_to_snowflake_etl_dag.py:211} ERROR - Kafka Consumer failed with error: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[2024-11-25T15:55:19.313+0000] {python.py:177} INFO - Done. Returned value was: False
[2024-11-25T15:55:19.327+0000] {taskinstance.py:1322} INFO - Marking task as SUCCESS. dag_id=kafka_to_snowflake_pipeline, task_id=start_kafka_consumer, execution_date=20241124T155442, start_date=20241125T155519, end_date=20241125T155519
[2024-11-25T15:55:19.338+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2024-11-25T15:55:19.353+0000] {taskinstance.py:2582} INFO - 1 downstream tasks scheduled from follow-on schedule check
